### ISSUE TITLE
modify FSC-A and SSC-A for different cut-off

### ISSUE THREAD

**Issue by star9926** [cran/beadplexr#1]
Hi, Ulrik,

Super excited to use Beadplexr for Legendplex analysis, while I am wondering if it is possible to chage the cut-off for FSC-A and SSC-A with bead A and B. Since I used different kit from Biolegend named mouse inflammation panel (13 plex), recognization for bead A and B based on default threshold of bead A and B was not ideal form my side. I am wondering how to change the default, and decide on the optimal parameter for that?

Thanks!  :D

Best regards,
Na

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by star9926** [comment]
got it, thanks for your information, filter(`FSC-A` > 4e5L, `FSC-A` < 6.3e5L). :D
